services:

  wikipedia-mcp:
    image: mcp/wikipedia-mcp
    container_name: wikipedia-mcp
    command: --transport sse --host 0.0.0.0 --port 8080 --enable-cache --language en
    restart: always
    ports:
      - "6080:8080"

# Only stdio
#  duckduckgo:
#    image: mcp/duckduckgo
#    container_name: duckduckgo
#    command: python -m duckduckgo_mcp_server.server --transport sse --host 0.0.0.0 --port 8080
#    restart: always
#    ports:
#      - "6081:8080"
