#OPENAI_API_KEY: ollama
#OPENAI_BASE_URL: http://localhost:11434/v1

spring:
  application:
    name: Gekko
  ai:
    #    openai:
    #      api-key: ${OPENAI_API_KEY:ollama}
    #      base-url: ${OPENAI_BASE_URL:http://localhost:11434/v1}
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}

embabel:
  agent:
    platform:
      scanning:
        bean: false

  models:
    default-llm: qwen2.5:7b-instruct
    default-embedding-model: nomic-embed-text:latest
    llms:
      best: qwen2.5:7b-instruct
      cheapest: ministral-3:3b
    embedding-services:
      best: nomic-embed-text:latest
      cheapest: nomic-embed-text:latest
  agent-platform:
    ranking:
      llm: qwen2.5:7b-instruct

spring.profiles.active: base,app,observability,local
logging:
  level:
    com.embabel: WARN
    com.embabel.agent.api.annotation.support.AgentMetadataReader: WARN
