spring:
  application:
    name: Gekko
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}

embabel:
  agent:
    platform:
      scanning:
        bean: false

  models:
    default-llm: deepseek-r1:8b
    default-embedding-model: nomic-embed-text:latest
    llms:
      best: qwen3:8b
      cheapest: deepseek-r1:8b
    embedding-services:
      best: nomic-embed-text:latest
      cheapest: nomic-embed-text:latest
  agent-platform:
    ranking:
      llm: deepseek-r1:8b

spring.profiles.active: base,app,observability,local
logging:
  level:
    com.embabel: WARN
    com.embabel.agent.api.annotation.support.AgentMetadataReader: WARN
