embabel:
  agent:
    platform:
      scanning:
        bean: false
  models:
    default-llm: qwen3:14b
    default-embedding-model: nomic-embed-text:latest
    llms:
      best: qwen3:14b
      cheapest: qwen3:14b
    embedding-services:
      best: nomic-embed-text:latest
      cheapest: nomic-embed-text:latest
  agent-platform:
    ranking:
      llm: qwen3:14b

spring.profiles.active: base,observability,local
logging:
  level:
    com.embabel: INFO
    com.embabel.agent.api.annotation.support.AgentMetadataReader: INFO
